### ISSUE TITLE
Add theme to the site

### ISSUE THREAD

**Issue by zenorocha** [dracula/coteditor#1]
Hey @yougotwill, I just wanted to let you know that this theme is on the site now: https://draculatheme.com/coteditor

Thanks for doing this theme!

**Comment by yougotwill** [comment]
@zenorocha Great news! Thanks for adding it. Looking forward to seeing Dracula Pro 😄

**Comment by zenorocha** [comment]
Yaaay! Thanks @yougotwill ;)
